### ISSUE TITLE
StakeUtils contract users can potentially be indefinitely locked out of unstaking their tokens

### ISSUE THREAD

**Issue by kinspotting** [api3dao/api3-dao#137]
Users currently use function `scheduleUnstake()` to schedule unstaking their tokens. This function calls `getValue()`, which in turn searches the given array for the checkpoint at the current block. If either of the `totalStaked` or `totalShares` arrays were to eventually grow to a sufficiently large size, this binary search will exceed the current block gas limit, and `getValue()`/`getValueAt()` will always fail. This will result in `scheduleUnstake()` always failing, and in turn all contract users will be indefinitely`prevented from unstaking their tokens.

**Comment by bbenligiray** [comment]
Closed by https://github.com/api3dao/api3-dao/pull/134
