### ISSUE TITLE
Have two pairs of Voting apps and Agents

### ISSUE THREAD

**Issue by kinspotting** [api3dao/api3-dao#141]
Agent #1 holds a small amount of funds and the Voting app #1 parameters are lower.

Agent #2 is the API3 token contract owner, holds the majority of the funds and the Voting app #2 parameters are higher (for example, you can't pass proposals with less than 50%).

**Comment by bbenligiray** [comment]
We will also require two Agent roles in the pool contract
https://github.com/api3dao/api3-dao/blob/4405a48fa0097ea60a47c56c4e0ae6e30e779ea5/packages/pool/contracts/StateUtils.sol#L47
one to control claims manager statuses, the other to set rewards parameters (which we're okay with them being easily changeable)

**Comment by bbenligiray** [comment]
Agent50 (potential attack vectors)
https://github.com/api3dao/api3-dao/blob/4405a48fa0097ea60a47c56c4e0ae6e30e779ea5/packages/pool/contracts/StateUtils.sol#L204
https://github.com/api3dao/api3-dao/blob/4405a48fa0097ea60a47c56c4e0ae6e30e779ea5/packages/pool/contracts/StateUtils.sol#L275
https://github.com/api3dao/api3-dao/blob/4405a48fa0097ea60a47c56c4e0ae6e30e779ea5/packages/pool/contracts/StateUtils.sol#L313

Agent15
https://github.com/api3dao/api3-dao/blob/4405a48fa0097ea60a47c56c4e0ae6e30e779ea5/packages/pool/contracts/StateUtils.sol#L218
https://github.com/api3dao/api3-dao/blob/4405a48fa0097ea60a47c56c4e0ae6e30e779ea5/packages/pool/contracts/StateUtils.sol#L237
https://github.com/api3dao/api3-dao/blob/4405a48fa0097ea60a47c56c4e0ae6e30e779ea5/packages/pool/contracts/StateUtils.sol#L253
https://github.com/api3dao/api3-dao/blob/4405a48fa0097ea60a47c56c4e0ae6e30e779ea5/packages/pool/contracts/StateUtils.sol#L291

**Comment by BritikovKI** [comment]
Actually we need to deploy those voting apps and agents inside of Api3Template, so I will reopen this issue to achieve this goal.
