### ISSUE TITLE
Pool: A potentially better parameter ordering for the 'Withdrawn" event

### ISSUE THREAD

**Issue by gwn** [api3dao/api3-dao#167]
I'm definitely no expert and I only wanted to think out loud.

There are several events that are similar to the `Withdrawn` event such as `Deposited`, `Staked` and `Unstaked` and they have as their first parameter the target address.  But this is not the case for `Withdrawn` as it has the sender address as the first parameter and the target address the second. And I cannot reliably use the sender address here as the sender & receiver addresses can be different in the case of `Withdrawn`. Ref: https://github.com/api3dao/api3-dao/blob/develop/packages/pool/contracts/TransferUtils.sol#L54-L57

In my web client work I wanted to fetch all those events at once, but filtered for a given target address. Apparently this would've been possible if the target address was the first parameter in all those events. But because it isn't, I had to make two separate queries. (Ref: https://docs.ethers.io/v5/concepts/events/#events--filters)

This is so not a big deal and I actually care about consistency & implementation simplicity more than performance. But the implementation is still relatively straightforward even if we have to make 2 separate queries.

Just looking for some thoughts, if / when you have time for this.

**Comment by bbenligiray** [comment]
I think the current way it is better because the first argument is always the user address. Also this is probably not relevant anymore with Convenience.sol.

**Comment by gwn** [comment]
> I think the current way it is better because the first argument is always the user address. Also this is probably not relevant anymore with Convenience.sol.

I understand, you're making sense. And yeah, Convenience definitely already made this simpler. Thank you for taking the time to think about this.
