### ISSUE TITLE
Token holders with 2% of the tokens can block any user from being delegated to

### ISSUE THREAD

**Issue by BritikovKI** [api3dao/api3-dao#183]
This attack requires 20 proposals to be made in a single week, which means there is proposal spam and that is a problem in itself (so many proposals can’t be expected to be evaluated by the voters). If that happens frequently enough to be a problem, the DAO should increase proposalVotingPowerThreshold. 

One thing that could greatly alleviate the risk is preemptively increasing MAX_INTERACTION_FREQUENCY and proposalVotingPowerThreshold (for example 20->40 and 0.1%->0.5%, making the attack 10 times as difficult).

Possibly there are other solutions

**Comment by BritikovKI** [comment]
We can possibly limit an amount of proposals per week, if this will make any sense, or introduce a time limit after doing a proposal..

**Comment by BritikovKI** [comment]
As well we may limit amount of active proposals noone will need 20 active proposals in the network, thay may be handled successively, not concurrently

**Comment by bbenligiray** [comment]
This is closed here https://github.com/api3dao/api3-dao/pull/218
