### ISSUE TITLE
Vulnerabilities in package dependencies

### ISSUE THREAD

**Issue by BritikovKI** [api3dao/api3-dao#185]
We need to research if it possible to change our dependencies versions(It may break the aragon)

**Comment by BritikovKI** [comment]
Not relevant anymore

**Comment by bbenligiray** [comment]
How so?

**Comment by BritikovKI** [comment]
Oh, my bad, I thought it was about github dependency warning

**Comment by BritikovKI** [comment]
Ok, root is fixed, `pool` is impossible to fix because of `solidity-coverage` and `ethereum-waffel` version inconveniences....

**Comment by BritikovKI** [comment]
Will leave it here, to check on after, right now it's not a priority because it will take a lot of time to reconfigure propperly....
