### ISSUE TITLE
setDAOApps is callable by anyone

### ISSUE THREAD

**Issue by BritikovKI** [api3dao/api3-dao#190]
The issue here is that there is circular dependency between the pool and the DAO and they are deployed in two separate transactions.A warning for the deployer/user to check that the DAO apps are set correctly would be useful (both in docs and the audit report).

**Comment by bbenligiray** [comment]
The proposed solution doesn’t prevent frontrunning because the pool contract is not deployed as a part of `Api3Template.newInstance()`. Add the `newInstance()` and `setDaoApps()` calls in the deployment script and as a part of the script check that they are executed correctly.

**Comment by BritikovKI** [comment]
I don't think it's relevant anymore
