### ISSUE TITLE
How to deploy DAO contracts

### ISSUE THREAD

**Issue by Siegrift** [api3dao/api3-dao#217]
Hi, 

### What I want to do

I'd like to deploy the DAO contracts. I tried running `npm run deploy:rinkeby` but that will only deploy the `Api3Template` and I want to also create a new DAO instance from it - by calling `Api3Template.newInstance` .

### What I am doing so far

I have created this snippet:
```js
/*global artifacts, web3, Promise*/
// NOTE: The whole script is inspired by 'api3template.js'
const { hash: namehash } = require('eth-ens-namehash')

const { getTemplateAddress } = require('@aragon/templates-shared/lib/ens')(web3, artifacts);
const { getInstalledAppsById, getInstalledApps } = require('@aragon/templates-shared/helpers/events')(artifacts);

const Api3Voting = artifacts.require('Api3Voting');
const Api3Template = artifacts.require('Api3Template');
const Api3Pool = artifacts.require('Api3Pool');
const Agent = artifacts.require('Agent');

module.exports = async (callback) => {
  try {
    const [deployer] = await new Promise((resolve, reject) => {
      web3.eth.getAccounts((err, accounts) => {
        if (err) {
          return reject(err)
        }
        resolve(accounts)
      })
    })

    let api3Template, receipt1, api3Pool;

    const API3_POOL_ADDRESS = '0x69c40A6908Ba996A0c22110117E53e77Fde5bB75'.toLowerCase()

    const SUPPORT_1 = 80e16;
    const ACCEPTANCE_1 = 40e16;
    const VOTING_DURATION_1 = 100;

    const SUPPORT_2 = 50e16;
    const ACCEPTANCE_2 = 20e16;
    const VOTING_DURATION_2 = 60;


    console.log('1')
    console.log('1.2', await getTemplateAddress()) // TODO: fixme here
    api3Template = Api3Template.at(await getTemplateAddress());
    console.log('2')
    api3Pool = Api3Pool.at(API3_POOL_ADDRESS);
    console.log('3')
    receipt1 = await api3Template.newInstance('api3template', (api3Pool.address), [SUPPORT_1, ACCEPTANCE_1, VOTING_DURATION_1], [SUPPORT_2, ACCEPTANCE_2, VOTING_DURATION_2], { from: deployer });
    console.log('4')

    const installedApps = getInstalledAppsById(receipt1);
    const votingApps = getInstalledApps(receipt1, namehash('api3voting.aragonpm.eth'));
    const votingMain = Api3Voting.at(votingApps[0]);
    const votingSecondary = Api3Voting.at(votingApps[1]);
    const agentMain = Agent.at(installedApps.agent[0]);
    const agentSecondary = Agent.at(installedApps.agent[1]);

    console.log(JSON.stringify({
      votingPrimary: votingMain.address,
      votingSecondary: votingSecondary.address,
      agentPrimary: agentMain.address,
      agentSecondary: agentSecondary.address
    }, null, 2))
    // await api3Pool.setDaoApps(agentMain.address, agentSecondary.address, votingMain.address, votingSecondary.address);
    console.log('Do not forget to call api3Pool.setDaoApps(agentMain.address, agentSecondary.address, votingMain.address, votingSecondary.address)!!!')

  } catch (error) {
    callback(error);
  }
  callback();
};
```

which is based on the test file. This works kinda OK - I just set the `API3_POOL_ADDRESS` and execute the script.
It works for localhost, but when I try executing it on ropsten/rinkeby I get this error:
```
BigNumber Error: new BigNumber() not a base 16 number:
```
and the function call that throws is `await getTemplateAddress()`

### What I need help with

I am using hardhat-deploy and it seems aragon contracts can't be deployed like that as they are compiled under the hood by the aragon packages, which use truffle and web3.

I am fine with using something like the script above, but **I need it to work for all networks** (localhost, ropsten, mainnet...).
Can you please tell me, what did you use to deploy to rinkeby? Or better, can you provide me **instructions how to deploy the DAO to my target chain**? 

Thank you.

**Comment by Siegrift** [comment]
@kinspotting @BritikovKI

**Comment by bbenligiray** [comment]
Please address this ASAP, it's blocking and should have been there even before the audits.

**Comment by Siegrift** [comment]
Adding @andreogle for visibilty

**Comment by BritikovKI** [comment]
Hello there. That is actually pretty complicated. At first, if you aren't using rinkeby you will need to deploy `api3voting` app on the network you're going to use. Actually there is a script `publish:rinkeby` in the voting app for rinkeby right now, but it is pretty simple to change for any other network. 
To deploy voting app, you'll need to open `buidler.config.json`, add config for the network you are planning to deploy on, like this one:
```
    rinkeby: {
      url: 'https://rinkeby.infura.io/v3/4c9049736af84c46ad0972910df0476a',
      chainId: 4,
      accounts: ['private_key'],
      gasLimit: 'auto',
      gasPrice: 1000000000,
    },
```
With rpc provider and a private key from which to deploy, then you'll need to run this command from terminal:
```sh
buidler publish minor --network your_network
```
Ok, now you'll be able to deploy DAO.
To deploy DAO on your target chain is actually should be pretty simple. You need to create `.aragon` folder with config-file called `<your-network>_key.json` file(for Rinkeby it will be `rinkeby_key.json`) in your home directory, it should look like this:
```json
{
  "rpc": "https://rinkeby.infura.io/v3/4c9049736af84c46ad0972910df0476a",
  "keys": [
    "private_key_from_which_to_deploy"
  ]
}
```
Then you just need to run 
```sh
npm run deploy:your_network 
```
 from the `dao` directory. This should be it

**Comment by Siegrift** [comment]
I was able to deploy the voting app on ropsten, but I am still getting an error on on the second part - deploying the DAO.

I have pulled the recent `develop` branch - thank you for also setting the DAO apps and providing me the addresses I want.

However, when I run 
```bash
npm run deploy:ropsten
``` 

I get the following error:

```
Using network 'ropsten'.

=========
# Api3Template:
Address: 0xa2962c2cabfe34b7bac9557241016ed366cda48d
Transaction hash: 0xd78dad5fca720a6670910bba4191bd605e72196ac7c2188acf2a11e3824a9fdd
Compiler: solc@0.4.24+commit.e67f0147.Emscripten.clang (Optimizer: 10000 runs)
Compiled at: 2021-05-22T10:21:42.339Z
=========
Transaction: 0xd7a734f6b9943d43624bb3f809ce62161cefacf2285226c12a57844ef3268062 exited with an error (status 0).
Please check that the transaction:
    - satisfies all conditions set by Solidity `require` statements.
    - does not trigger a Solidity `revert` statement.

error Command failed with exit code 1.
```

This doesn't happen on `localhost`.

**Comment by Siegrift** [comment]
Also, I am not sure what do skip and what not when I want to deploy to `rinkeby` as well. Ideally I would want to have it deployed on both.

**Comment by BritikovKI** [comment]
> I was able to deploy the voting app on ropsten, but I am still getting an error on on the second part - deploying the DAO.
> 
> I have pulled the recent `develop` branch - thank you for also setting the DAO apps in the pool and providing me the addresses I want.
> 
> However, when I run
> 
> ```shell
> npm run deploy:ropsten
> ```
> 
> I get the following error:
> 
> ```
> Using network 'ropsten'.
> 
> =========
> # Api3Template:
> Address: 0xa2962c2cabfe34b7bac9557241016ed366cda48d
> Transaction hash: 0xd78dad5fca720a6670910bba4191bd605e72196ac7c2188acf2a11e3824a9fdd
> Compiler: solc@0.4.24+commit.e67f0147.Emscripten.clang (Optimizer: 10000 runs)
> Compiled at: 2021-05-22T10:21:42.339Z
> =========
> Transaction: 0xd7a734f6b9943d43624bb3f809ce62161cefacf2285226c12a57844ef3268062 exited with an error (status 0).
> Please check that the transaction:
>     - satisfies all conditions set by Solidity `require` statements.
>     - does not trigger a Solidity `revert` statement.
> 
> error Command failed with exit code 1.
> ```
> 
> This doesn't happen on `localhost`.

OK, I suppose there might be some possible errors, have you uncommented api3voting hash in the `Api3Template.sol` file?

There are two different aragonpm registry hashes in the smart contract, one is for the testing, another one is for the deployment. Comments describe which you need to comment, and which to uncomment...

**Comment by BritikovKI** [comment]
> Also, I am not sure what instructions to skip and which not when I want to deploy to `rinkeby`.
> Ideally I would want to have it deployed on both.

You' may skip api3voting deployment and changing the config files. But in the `deploy.js` of `dao` you'll need to change the value of `TEMPLATE_NAME`.

**Comment by Siegrift** [comment]
Thanks, that helped me deploy to ropsten once. However how can I redeploy? 

I have commented out the testing voting app ID and uncommented the rinkeby/mainet (which I used for ropsten as well).
```
   // Record below is ID for Rinkeby/Mainnet
   bytes32 constant internal API3_VOTING_APP_ID = 0x323c4eb511f386e7972d45b948cc546db35e9ccc7161c056fb07e09abd87e554;

    // Record below is ID for testing
    // bytes32 constant internal API3_VOTING_APP_ID = 0x727a0cf100ef0e645bad5a5b920d7fb71f8fd0eaf0fa579c341a045f597526f5;
```

however, getting the same error:
```
Using network 'ropsten'.

=========
# Api3Template:
Address: 0x44f46396c09c1c04eb7df6a2da45d5db02ad6324
Transaction hash: 0x53fe6c40fff0cf8d61d61e97ec854506143a402b91c0b881c3a76b11b5e052e0
Compiler: solc@0.4.24+commit.e67f0147.Emscripten.clang (Optimizer: 10000 runs)
Compiled at: 2021-05-24T07:50:27.419Z
=========
Transaction: 0x5715ed9d3744e04a8c42264878ea87e8dec7805c9e32b70c9d2eea47f0b5be09 exited with an error (status 0).
Please check that the transaction:
    - satisfies all conditions set by Solidity `require` statements.
    - does not trigger a Solidity `revert` statement.
```

**Comment by Siegrift** [comment]
I've manged to figure out what was the problem, I needed to change the `TEMPLATE_ID` - @BritikovKI Now that I think of it, that's what you said and I've just misunderstood.

Anyway, just to clarify a few things and extra information for future people stumbling on this...

#### Running IPFS locally

In order to publish the `api3-voting` app, you will need to be running IPFS locally - it took me some time, but then I've realized you can just use the aragon CLI which can run IPFS for you. See: https://hack.aragon.org/docs/guides-faq#propagating-your-content-hash-through-ipfs

For completeness, you can can do:
1. Install the CLI using:  `npm install --global @aragon/cli` 
2. Run IPFS locally: `aragon ipfs start`
 
 #### Arapp.json configuration
 
 The registry should be the ENS address on target chain.
 
 #### Other notes
 
 1. It's enough to deploy the voting app once - you don't need to republish every time you want to deploy new DAO
 2. After voting app is deployed you may deploy the DAO using the `Api3Template` 
 3. As of now you need to run `npm run test` to make sure the pool contract is imported into this subpackage
 4. You can only have a single DAO with the same `TEMPLATE_NAME` - but it can be anything, as long as it hasn't been used when deploying another instance
 5. When deploying to localhost use voting app ID inside `Api3Template`  `0x727a0cf100ef0e645bad5a5b920d7fb71f8fd0eaf0fa579c341a045f597526f5` otherwise use the other one - I was a bit confused by the comments (wasn't sure what to use for ropsten).
 
 Anyway, I'll need to make some small changes to the deploy script so I'll follow up this issue with a PR.
 Thanks for help :)

**Comment by Siegrift** [comment]
Actually, @BritikovKI I am unable to re-deploy to rinkeby - for localhost I can just change the `TEMPLATE_NAME` and it works.
For rinkeby I have tried deploying via different accounts - my own and also the one that was specified in `api3-voting` .

**Comment by Siegrift** [comment]
I mean calling `npm run deploy:rinkeby` with a different `TEMPLATE_NAME`

**Comment by BritikovKI** [comment]
Hmmm, that's strange, like old proverb says: "It works on my computer" :-) What is the error that you are receiving during the deployment?

**Comment by Siegrift** [comment]
Can you check this out https://github.com/api3dao/api3-dao/pull/248 ?

The error is the standard revert with no additional information
```
Using network 'rinkeby'.

=========
# Api3Template:
Address: 0x849c9cfa61bc50e5e9f6bbd538c06e064905f4e0
Transaction hash: 0x43303824df7d7e17890225f57837b96431aa31530ea819b77087b28eb203c9d8
Compiler: solc@0.4.24+commit.e67f0147.Emscripten.clang (Optimizer: 10000 runs)
Compiled at: 2021-05-24T15:42:01.917Z
=========
Transaction: 0x833411cd599ce5544cdaaf5cf760c88bb808f8f8b52199cfdc7a74a48ff49ca4 exited with an error (status 0).
Please check that the transaction:
    - satisfies all conditions set by Solidity `require` statements.
    - does not trigger a Solidity `revert` statement.
```

**Comment by BritikovKI** [comment]
Ok, from the looks of internal transactions this error happened to me when I provided the wrong API3voting id for the aragonpm management, check `Api3Template.sol`, is Voting app id correct there?

**Comment by Siegrift** [comment]
Yep I am using the one for testnet (`0x323c4eb511f386e7972d45b948cc546db35e9ccc7161c056fb07e09abd87e554`)

**Comment by BritikovKI** [comment]
Hmm, that's really strange, I'll try to replicate the error locally, I've encountered this error because of the problem I've mentioned in my comment. I'll do it from your branch....

**Comment by Siegrift** [comment]
For reference, this is my `rinkeby_key.json`:
```
{
  "rpc": "https://rinkeby.infura.io/v3/1c7314d556ca48208f8c7e1fe33e19c6",
  "keys": [
    "ff5886c7e52052fc95e4bd6956b1e420d10693e62fbe506d61fa25b152093d54"
  ]
}
```

I've tried other account too, but got the same result.

**Comment by BritikovKI** [comment]
Ok, I actually figured out what the problem is, and it is pretty important stuff, unfortunately, during some of the commits someone has changed Api3Voting, and especially `initialize` function which is being called from `api3template`, this means that I'll need to update api3voting on rinkeby, I'll fix it today, check that your PR is working and approve it then

**Comment by BritikovKI** [comment]
That's it, deployment is working everywhere right now

**Comment by Siegrift** [comment]
Not sure what changes have you made, but now I am not able to deploy to rinkeby nor ropsten.

**Comment by Siegrift** [comment]
Ok, my bad I forgot to switch `API3_VOTING_APP_ID` in the contract.
I tried again and it worked :) 

Thanks for help, we can close this issue.
