### ISSUE TITLE
First-party oracle registry

### ISSUE THREAD

**Issue by bbenligiray** [api3dao/api3-dao#25]
In the Airnode protocol, an API provider is represented by an ID (`bytes32`), which is derived from the API provider private key and is identical for all chains. API providers announce their `providerId`s over public channels (Twitter, API docs, etc.) which should allow people to match the two. Instead of having to do this all the time, the DAO keeps a registry that matches `providerId`s to API provider name/URL pairs. The DAO interface should allow proposals to update the registry.

**Comment by benefacto** [comment]
@cyclomancer TBD

**Comment by benefacto** [comment]
Out of scope for now
