### ISSUE TITLE
Upgrade solidity version and use the same version of open zepellin contracts

### ISSUE THREAD

**Issue by Siegrift** [api3dao/api3-dao#252]
Hi, 

It would be nice if all the contracts used the same solidity version as well as depend on open zepelling contracts at the same version. For now, some files use 0.8.4 and some 0.6.12.

Also, the new Convenience contract (package) is using `"@openzeppelin/contracts": "^4.1.0",` while the pool uses `"@openzeppelin/contracts": "^3.4.1",`.

**Comment by BritikovKI** [comment]
Hello, I think this is impossible to do everywhere, because our `api3voting` is using Solidity 0.4.24 and `dao` is using 0.4.24... So it wouldn't make that my change anyway, but OK, will try to synchronize `pool` and `convenience`, because that's at least something....

**Comment by Siegrift** [comment]
Yeah, actually the only problem for me is the conflicting `"@openzeppelin/contracts` dependency, but I have a workround in place.

If there is some more pressing work, feel free to leave this until theres more time :)

**Comment by bbenligiray** [comment]
>  will try to synchronize pool and convenience

This is done, we kept the Aragon related contracts at 0.4.24 on purpose
