### ISSUE TITLE
Identity registry

### ISSUE THREAD

**Issue by bbenligiray** [api3dao/api3-dao#33]
We will need an authoritative way to match addresses to names and vice versa for voting power delegation and keeping track of compensations. Having this maintained by the DAO like the first-party oracles (https://github.com/api3dao/api3-dao/issues/25) feels like an overkill, but making it self-served enables shenanigans like registering with similar names to others. Would like your input about this.

**Comment by ErichDylus** [comment]
Will be important to ensure express consent and personal data privacy/GDPR compliance with tying identity to addresses. Perhaps a Keybase-like verification with ability for the address owner to delete when not actively delegating or being compensated.

**Comment by benefacto** [comment]
Part out of date, part front end problem

**Comment by benefacto** [comment]
Confirming whether this is still something that needs to be handled

**Comment by benefacto** [comment]
Out of scope for now
