### ISSUE TITLE
Better staking UX

### ISSUE THREAD

**Issue by bbenligiray** [api3dao/api3-dao#34]
(This was talked about in the call) Currently, there are three states a user can be in:
- Unpooled: No rewards, no voting power, no insurance risk
- Pooled: No rewards, no voting power, insurance risk
- Staked: Rewards, Voting power, insurance risk

A pooled user has to stake each epoch to receive voting power and staking rewards in the next epoch. This was done for three reasons (as far as I can remember):
1. We don't want to distribute revenue to people who have lost access to their pooled funds
1. We don't want people to hit-and-run (stake an hour before the epoch ends, collect the reward and unstake)
1. Each staking update by the user acts as a snapshot that allows us to query the voting power of a user at an epoch (the DAO contract we were planning to use did not have this built-in)

(1) is solved because [we are no longer distributing revenue](https://medium.com/api3/api3-tokenomics-update-f032d6e49b30).

(2) can be solved by using a non-zero [`unpoolWaitingPeriod`](https://github.com/api3dao/api3-dao/blob/f491bb7390683687abec80f26e410c7282b74def/packages/contracts/api3-pool/contracts/Api3State.sol#L87) (we were [planning](https://github.com/api3dao/api3-dao/blob/f491bb7390683687abec80f26e410c7282b74def/packages/contracts/api3-pool/contracts/Api3State.sol#L85-L86) to wait for insurance to be implemented before to set it to a non-zero value).

Voting power snapshots will be taken by MiniMe, so (3) is no longer needed (correct me on this).

Then, we can merge the pooled and staked states into one, and pay out rewards to all pooled users without requiring them to make a transaction to renew their stake each epoch.

**Comment by bbenligiray** [comment]
We currently require the users to stake each week, mostly to create a vesting that will pay out inflationary rewards
https://github.com/api3dao/api3-dao/blob/de83826219714659f9950c4dd7e0915e3e158543/packages/contracts/api3-pool/contracts/StakeUtils.sol#L105
Although this 1 year vesting is desirable, it's not as necessary with the new inflation mechanics. So in case we can't remove the need for this weekly transaction (by using MiniMe for example), then we are fine with having inflationary rewards be paid out instantly. So the inflationary rewards would simply be added to the pooled tokens, which means each share the stakers would hold would be worth more tokens.
This would also be relevant to the dashboard design, it would simplify it substantially.

**Comment by benefacto** [comment]
Possibly out of date, baked in
