### ISSUE TITLE
Support for making/verifying arbitrary proposals

### ISSUE THREAD

**Issue by bbenligiray** [api3dao/api3-dao#38]
Currently, we make proposals to make arbitrary transactions through the Agent app, then push the transaction specifications to a [repo](https://github.com/api3dao/proposal-verifier/tree/master/proposalSpecs), which other voters can [verify](https://github.com/api3dao/proposal-verifier/#instructions).

This is not optimal because the majority of the voters will not be able to use this tool to verify the transactions. We need this to be built in to the dashboard so that all voters will be able to verify the specifications of arbitrary transaction proposals. Ideally, the specs would not have to be hosted on Github (on IPFS maybe?).

**Comment by cyclomancer** [comment]
We're looking at using the 3Box APIs (interface with IPFS) to handle both this and the user profiles in a single integration

**Comment by benefacto** [comment]
This will be completed in the next undertaking
