### ISSUE TITLE
User Interface Implementation

### ISSUE THREAD

**Issue by mrrobot16** [api3dao/api3-dao#66]
This is a breakdown of the pieces needed to implement UI styling from Mockups.

Figma: https://www.figma.com/file/NiDnUxkSucJmdbHbo9UrAC/API3-DAO?node-id=327%3A432
Video Walthrough: https://drive.google.com/file/d/12m5hljkkB92ZcWCbA3o-SBs8NRbpJCH8/view

**Actions/Functionalities:**

- [ ] Deposit to API3 contract to able to stake API3.
- [ ] Stake API3 tokens after deposit.
- [ ] Withdrawal after staking
- [ ] Unstake after cooldown
- [ ] Delegates user tokens/vote weight/power to another address.
- [ ] Undelegate weight power & tokens.
- [ ] Vote
- [ ] Unvote/Change Vote
- [ ] Slideshow that shows tips of how to use the ui/app.
- [ ] Fetch Insurance pool information for Landing
- [ ] Cooldown Ends and it will enable users to unstake.

**List of Screens/Pages:**
- [x] UserDashboard
- [x] Landing
- [x] Proposal Details

**List of Components:** 
- [x] Header/Top Navbar
- [ ] Proposals Count
- [x] ConnectWallet Button
- [ ] DelegateVotes Button
- [ ] Vote Button
- [ ] Direct Vote(For & Against) skip VotePopout.
- [x] AccountInfo
- [ ] Horizontal/Vertical/ Navigation/menu bar it shows a number of proposals be recently created.
- [x] Slideshow
- [ ] Insurance Pool box to be reused in several pages
- [x] Number Components(Percentage, Formatted decimals and corresponding styling)
- [ ] Popout for proposal creation and other actions(Deposit,Withdrawal, Vote, Stake, Unstake, etc) with same layout.
- [ ] Confirm Popout as well
- [x] Countdown
- [x] List Proposals
- [x] Proposal item in list, display info:date, number, address, duration time(counter of days hours minutes), status, etc
- [ ] Proposal item horizontal progress bar(percentage) changes color depending of proposal status.
- [x] Proposal Details Content: Counter remaing time of proposal, Vote Button, User's Voting weight, Delegate Votes Button, status(active, rejected, passed, etc), Summary & link for discussion forum.
- [x] Icons for actions & statuses.
- [ ] Help icon hover display small box with text

**Comment by benefacto** [comment]
[This](https://github.com/api3dao/api3-dao/issues/84#issuecomment-779388596) will be in scope of this
