### ISSUE TITLE
UI & stylings feedback

### ISSUE THREAD

**Issue by mrrobot16** [api3dao/api3-dao#77]
- [ ] change text below the countdown box.
- [ ] create a container/box for when time is up
- [ ] vertical Line in Sidebar that indicate what page user is at is missing when users is in landingpage "/"
- [ ] “how it work”” is a full screen overlay when user clicks the “how it works” text in WalletConnected Dashboard
- [ ] overlay for screens 1024width.
- [ ] boxes should not grow on larger screens but it should decrease in smaller screens.
- [ ] replicate https://app.compound.finance/ scalability/responsiveness of boxes size.
- [ ] implement global stylings
- [ ] add progress animation based on percentage number
- [ ] background linear gradient like current api3.org landing page.
- [x] create reuseable Modal
- [x] disable auto-carousel.
- [x] make the linear gradient border for whom you voted(ProposalItem)
- [x] added button disable styling when the Counter is active.
- [x] font size don’t match in insurance pool “total staked”
- [x] missing triangle icon next to wallet address. onClick should disconnect wallet?
- [x] missing carousel arrows
- [x] avoid navigating to dashboard if user has not connected wallet

General

- [ ] change to global styles
- [ ] Some numbers should have animation of increasing until the real number.
- [x] Missing Footer
- [x] Missing Linear gradient background
- [ ] Overlay for screens 1042width
- [ ] Boxes should not grow on larger screens but it should decrease in smaller screens
- [x] missing button style when is disabled
Header
- [x] Triangle Icon missing when the wallet is connected
- [x] Connected to _ is not 300 font weight

LandingPage/Dashboard
- [ ] “how it work”” is a full screen overlay when user clicks the “how it works” text in WalletConnected Dashboard (Figma screen missing).
- [ ] Change the style of the arrow on the carrousel
- [x] Carrousel shouldn't auto slide
- [x] Font size don’t match in insurance pool “total staked”

Proposals

- [x] Change the Triangle Icon with the amount of voters.

**Comment by yardiewizardie** [comment]
General 

- change to global styles
- Some numbers should have animation of increasing until the real number.
- Missing Footer
- Missing Linear gradient background
- Overlay for screens 1042width
- Boxes should not grow on larger screens but it should decrease in smaller screens

Header

- Triangle Icon missing when the wallet is connected
- Connected to _ is not 300 font weight

LandingPage/Dashboard

- Change the style of the arrow on the carrousel
- Carrousel shouldn't auto slide
- “how it work”” is a full screen overlay when user clicks the “how it works” text in WalletConnected Dashboard (Figma screen missing).
- Font size don’t match in insurance pool “total staked”

Proposals

- Change the Triangle Icon with the amount of voters.
