### ISSUE TITLE
List of the data need from API3 smart contracts

### ISSUE THREAD

**Issue by mrrobot16** [api3dao/api3-dao#78]
UI needs to fetch following data:
- [ ] annual rewards APY 
- [ ] annual inflation rate
- [ ] total API3 staked
- [ ] API3 staking target

**State variables**
-   uint256 public minApr = 2500000; // 2.5%
-   uint256 public maxApr = 75000000; // 75%
-   uint256 public stakeTarget = 10e6 ether; // 10M API3
-   uint256 public updateCoeff = 1000000;

**Getter functions**
- minApr()
- maxApr()
- stakeTarget()
- updateCoeff()
- currentApr()

**Comment by cyclomancer** [comment]
APY and inflation rate should be calculated from currentApr:

- Inflation: currentAPR * totalStaked / totalSupply / 100000000
- APY formula: https://www.bankrate.com/glossary/a/apy-annual-percentage-yield/

The `public` getters above should be good for everything except total staked, which I'll merge a custom getter `totalSupply()` for into `develop` tonight.

**Comment by cyclomancer** [comment]
To clarify: the `totalSupply()` used to calculate inflation is from the token contract, the `totalSupply()` for total staked comes from the pool contract. I'm giving the latter the same name for compatibility with Aragon.

**Comment by benefacto** [comment]
This is complete
