### ISSUE TITLE
User Interface Feedback

### ISSUE THREAD

**Issue by mrrobot16** [api3dao/api3-dao#84]

**Comment by heikkivanttinen** [comment]
The whole UI was very unrefined, so I asked our designers to polish it. You can find the updated design in the link below. Where the copy (text) deviates from the original design, use the original (there's also just some lorem ipsum in there atm).

https://www.figma.com/proto/xhC9gnteZ2DDmdPHWIie1v/API3-DAO-UI?node-id=41%3A3586&viewport=-891%2C551%2C0.5&frame-preset-name=Desktop&scaling=min-zoom

**Comment by heikkivanttinen** [comment]
Some comments (by page nr.):

All pages: Left-vertical menu needs tab names - not just icons. Top one should say "Dashboard", bottom one should say "Proposals".

1.
- "How this works" copy still WIP
- Capitalize "Rewards" in "Annual Rewards"
- Currently a typo in "Initiate Unstake"
4.
-"How many tokens would you like to unstake?" > "How many API3 would you like to unstake?"
-"TOKEN" > "API3"
5. 
-"Are you sure you would like to unstake 1,000 tokens? Lorem ipsum..." > "Are you sure you want to unstake 1,000 API3? Initiating unstake will start a 7-day cool-down period. During the cool-down period your tokens will remain in the insurance pool but do not earn staking rewards. After the cool-down period, you have 7 days to finalize the unstake."

Between unstake layout options 7/8/9, I think 7 is the best. 

12. 
- "0.1% My Voting Weight" > "My Voting Weight: 0.1%"
- "Delegate My Votes" > "Delegate My Vote"
13.
- Change "Against - For" from vertical to horizontal orientation, "For" on the left, "Against" on the right
- "Create Transaction" > "Vote" 
19.
- "Delegate my votes to:" > "Delegate my vote to:" 
- "Delegate Tokens" > "Delegate Vote"

**Comment by benefacto** [comment]
> 
> 
> The whole UI was very unrefined, so I asked our designers to polish it. You can find the updated design in the link below. Where the copy (text) deviates from the original design, use the original (there's also just some lorem ipsum in there atm).
> 
> https://www.figma.com/proto/xhC9gnteZ2DDmdPHWIie1v/API3-DAO-UI?node-id=41%3A3586&viewport=-891%2C551%2C0.5&frame-preset-name=Desktop&scaling=min-zoom

We will hold off on this pre-launch to support testing, proposal verification, and ensuring the UI is robust.

**Comment by ferdiozturk** [comment]
Messy layout on mobile. Android + Chrome
![Screenshot_20210302-201337_Chrome](https://user-images.githubusercontent.com/5754053/109702051-0ab5e080-7b94-11eb-806c-890d26f8f1a3.jpg)

**Comment by bbenligiray** [comment]
We have left the mobile layout out of scope for the launch. I think we should include it to the next iteration (for the new design). That being said, the issue above indeed looks terrible and should be easy to address (at least to some degree).

Proposal type names Type 1 and Type 2 are not descriptive. Rename Type 1 -> "Transfer", Type 2 -> "Update Parameters"

In the Type 1 modal, replace "Enter user's address here" with "Enter recipient's address here"

In the Type 2 modal:
- DAO Parameter to change -> DAO Parameter to Update
- Minimum voting weight to create a proposal -> Minimum Voting Weight to Create a Proposal
- The labels and textboxes/dropdowns are not aligned horizontally
- Stake target doesn't have a MAX value, get rid of that.
- APR Update Rate does not have a unit, remove "API3". Also make sure that you're not converting this value to Wei while interacting with the contract (unlike the stake target, which you should convert to Wei).
- In my opinion keep the % and API3 outside of the textbox. They are behaving very strangely.
- I can't seem to delete the contents of the percentage textboxes. I think when a parameter is selected from the dropdown, it's textbox should be empty, with the current parameter being displayed in gray (for all parameters, including the ones with the percentages).
- See the contract for valid parameter values, don't allow updates for invalid ones https://github.com/api3dao/api3-dao/blob/aa1eef8548633c75f648961200f6165c12d1d24c/packages/pool/contracts/GovernanceUtils.sol
- Missing a parameter here "Unstake Waiting Period". See the link to the contract above.
- I delete the contents of APR Update Rate, then I select Voting Weight from the parameters and I get the screenshot below
![Screenshot_2021-03-04 API3 DAO Decentralized API's for Web 3 0](https://user-images.githubusercontent.com/19530665/109956720-0ce38080-7cf5-11eb-8776-b45bd5332840.png)
- After I mess with the parameters in the modal, I close the modal and click New Proposal again. The parameters are as I've left them. I assume when it's integrated with the contract these will be repopulated with the current values.
- I can't type into the Reference field in the Type 2 modal

After I click New Proposal and close the modal, the New Proposal button gets an orange highlight. This is probably not intended.

![Screenshot from 2021-03-04 13-52-44](https://user-images.githubusercontent.com/19530665/109953451-21257e80-7cf1-11eb-9d97-b6eff6bd8f9b.png)

Is there any way we can see proposals, delegations, proposal parameter verification, etc.?

**Comment by mrrobot16** [comment]
> Some comments (by page nr.):
> 
> All pages: Left-vertical menu needs tab names - not just icons. Top one should say "Dashboard", bottom one should say "Proposals".
> 
> 
> * "How this works" copy still WIP
> * Capitalize "Rewards" in "Annual Rewards"
> * Currently a typo in "Initiate Unstake"
> 
> 
> -"How many tokens would you like to unstake?" > "How many API3 would you like to unstake?"
> -"TOKEN" > "API3"
> 5.
> -"Are you sure you would like to unstake 1,000 tokens? Lorem ipsum..." > "Are you sure you want to unstake 1,000 API3? Initiating unstake will start a 7-day cool-down period. During the cool-down period your tokens will remain in the insurance pool but do not earn staking rewards. After the cool-down period, you have 7 days to finalize the unstake."
> 
> Between unstake layout options 7/8/9, I think 7 is the best.
> 
> 
> * "0.1% My Voting Weight" > "My Voting Weight: 0.1%"
> * "Delegate My Votes" > "Delegate My Vote"
> 
> 
> * Change "Against - For" from vertical to horizontal orientation, "For" on the left, "Against" on the right
> * "Create Transaction" > "Vote"
> 
> 
> * "Delegate my votes to:" > "Delegate my vote to:"
> * "Delegate Tokens" > "Delegate Vote"

Thanks for the clarity we have addressed this :)

**Comment by heikkivanttinen** [comment]
> > The whole UI was very unrefined, so I asked our designers to polish it. You can find the updated design in the link below. Where the copy (text) deviates from the original design, use the original (there's also just some lorem ipsum in there atm).
> > https://www.figma.com/proto/xhC9gnteZ2DDmdPHWIie1v/API3-DAO-UI?node-id=41%3A3586&viewport=-891%2C551%2C0.5&frame-preset-name=Desktop&scaling=min-zoom
> 
> We will hold off on this pre-launch to support testing, proposal verification, and ensuring the UI is robust.

I notified you of the UI needing additional work 1 day after Hector had posted his initial Figma. The updated design was finished 10 days after that - 22 days ago. This would have given 3 weeks to this day to start on the implementation of the final design. Giving notice 19 days after the design was provided, that it's not going to be implemented, is not good operating procedure to say the least. You could have brought this up much earlier. If you ask us to provide comments in this Github issues page, we expect you to follow it and provide your feedback in a timely manner.

**Comment by heikkivanttinen** [comment]
> > Some comments (by page nr.):
> > All pages: Left-vertical menu needs tab names - not just icons. Top one should say "Dashboard", bottom one should say "Proposals".
> > 
> > * "How this works" copy still WIP
> > * Capitalize "Rewards" in "Annual Rewards"
> > * Currently a typo in "Initiate Unstake"
> > 
> > -"How many tokens would you like to unstake?" > "How many API3 would you like to unstake?"
> > -"TOKEN" > "API3"
> > 5.
> > -"Are you sure you would like to unstake 1,000 tokens? Lorem ipsum..." > "Are you sure you want to unstake 1,000 API3? Initiating unstake will start a 7-day cool-down period. During the cool-down period your tokens will remain in the insurance pool but do not earn staking rewards. After the cool-down period, you have 7 days to finalize the unstake."
> > Between unstake layout options 7/8/9, I think 7 is the best.
> > 
> > * "0.1% My Voting Weight" > "My Voting Weight: 0.1%"
> > * "Delegate My Votes" > "Delegate My Vote"
> > * Change "Against - For" from vertical to horizontal orientation, "For" on the left, "Against" on the right
> > * "Create Transaction" > "Vote"
> > * "Delegate my votes to:" > "Delegate my vote to:"
> > * "Delegate Tokens" > "Delegate Vote"
> 
> Thanks for the clarity we have addressed this :)

This was in response and as clarification to the polished UI spec provided 22 days ago. Since that spec is not going to be implemented for the first version, I'm not sure exactly what there is to address.

**Comment by benefacto** [comment]
> 
> 
> > > The whole UI was very unrefined, so I asked our designers to polish it. You can find the updated design in the link below. Where the copy (text) deviates from the original design, use the original (there's also just some lorem ipsum in there atm).
> > > https://www.figma.com/proto/xhC9gnteZ2DDmdPHWIie1v/API3-DAO-UI?node-id=41%3A3586&viewport=-891%2C551%2C0.5&frame-preset-name=Desktop&scaling=min-zoom
> > 
> > 
> > We will hold off on this pre-launch to support testing, proposal verification, and ensuring the UI is robust.
> 
> I notified you of the UI needing additional work 1 day after Hector had posted his initial Figma. The updated design was finished 10 days after that - 22 days ago. This would have given 3 weeks to this day to start on the implementation of the final design. Giving notice 19 days after the design was provided, that it's not going to be implemented, is not good operating procedure to say the least. You could have brought this up much earlier. If you ask us to provide comments in this Github issues page, we expect you to follow it and provide your feedback in a timely manner.

Hi Heikki, I'm sorry to hear that you weren't updated on what the front end team was working on and planning to work on. We had implementation of the revised mockups and addressing feedback from them in our backlog for some time but were uncertain as to whether we would have time to do so, given the timeline we were working under and the budgetary concerns, until quite recently. Our most recent meeting clarified that we would not have time to implement the revised mockups, since the team told that #38 was a higher priority and would take precedence, which I communicated to @bbenligiray and updated this issue. But it sounds like your were not kept in the loop there, so feel free to drop in our meetings as you like or direct message me on Discord so that we can arrange so other means of keeping you updated.

**Comment by mrrobot16** [comment]
- [ ] Proposal type names Type 1 and Type 2 are not descriptive. Rename Type 1 -> "Transfer", Type 2 -> "Update Parameters"

- [ ] In the Type 1 modal, replace "Enter user's address here" with "Enter recipient's address here"

In the Type 2 modal:

- [ ] DAO Parameter to change -> DAO Parameter to Update
- [ ] Minimum voting weight to create a proposal -> Minimum Voting Weight to Create a Proposal
- [ ] The labels and textboxes/dropdowns are not aligned horizontally
- [ ] Stake target doesn't have a MAX value, get rid of that.
- [ ] APR Update Rate does not have a unit, remove "API3". Also make sure that you're not converting this value to Wei while interacting with the contract (unlike the stake target, which you should convert to Wei).
-  In my opinion keep the % and API3 outside of the textbox. They are behaving very strangely.
- [ ] Can't seem to delete the contents of the percentage textboxes. I think when a parameter is selected from the dropdown, it's textbox should be empty, with the current parameter being displayed in gray (for all parameters, including the ones with the percentages).
- [ ] See the contract for valid parameter values, don't allow updates for invalid ones https://github.com/api3dao/api3-dao/blob/aa1eef8548633c75f648961200f6165c12d1d24c/packages/pool/contracts/GovernanceUtils.sol
- [ ] Missing a parameter here "Unstake Waiting Period". See the link to the contract above.
- [ ] delete the contents of APR Update Rate, then I select Voting Weight from the parameters and I get the screenshot below
![Screenshot_2021-03-04 API3 DAO Decentralized API's for Web 3 0](https://user-images.githubusercontent.com/19530665/109956720-0ce38080-7cf5-11eb-8776-b45bd5332840.png)
- [ ] After I mess with the parameters in the modal, I close the modal and click New Proposal again. The parameters are as I've left them. I assume when it's integrated with the contract these will be repopulated with the current values.
- [ ] can't type into the Reference field in the Type 2 modal
- [ ] After I click New Proposal and close the modal, the New Proposal button gets an orange highlight. This is probably not intended.
After I click New Proposal and close the modal, the New Proposal button gets an orange highlight. This is probably not intended.

![Screenshot from 2021-03-04 13-52-44](https://user-images.githubusercontent.com/19530665/109953451-21257e80-7cf1-11eb-9d97-b6eff6bd8f9b.png)

- [ ] Is there any way we can see proposals, delegations, proposal parameter verification, etc.?
